GROUP=com.bugsnag
VERSION_NAME=1.1.0

org.gradle.configuration-cache=true
org.gradle.unsafe.isolated-projects=true

POM_NAME=BugSnag Gradle Plugin
POM_ARTIFACT_ID=bugsnag-gradle-plugin
POM_PACKAGING=jar

POM_URL=https://github.com/bugsnag/bugsnag-gradle-plugin/
POM_SCM_URL=https://github.com/bugsnag/bugsnag-gradle-plugin/
POM_SCM_CONNECTION=scm:git:git://github.com/bugsnag/bugsnag-gradle-plugin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/bugsnag/bugsnag-gradle-plugin.git
POM_DESCRIPTION=Gradle plugin to automatically upload mapping files to BugSnag.

POM_LICENCE_NAME=MIT
POM_LICENCE_URL=http://opensource.org/licenses/MIT

POM_DEVELOPER_ID=bugsnag
POM_DEVELOPER_NAME=BugSnag
POM_DEVELOPER_URL=https://bugsnag.com

SONATYPE_STAGING_PROFILE=com.bugsnag
